name: CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  CDK_ENV: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-actions
          aws-region: ${{ env.AWS_REGION }}
      - name: Build CDK project
        run: npm run build
      - name: Build application image for tests
        run: |
          docker build -t app-under-test:${GITHUB_SHA::12} ./app
      - name: Run container tests
        run: |
          docker run --rm \
            -e DJANGO_SETTINGS_MODULE=testapp.settings \
            app-under-test:${GITHUB_SHA::12} \
            python manage.py test
      - name: Deploy infrastructure
        run: |
          npx cdk deploy NetworkStack-${CDK_ENV} DataStack-${CDK_ENV} AppStack-${CDK_ENV} \
            --require-approval never \
            -c env=${CDK_ENV}
